"""Creacion inicial SaaS

Revision ID: 0f23147c3831
Revises: 
Create Date: 2026-05-20 11:58:51.080247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f23147c3831'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('adm_client_settings',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_instance_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_token', sa.String(length=255), nullable=True),
    sa.Column('bot_system_prompt', sa.Text(), nullable=True),
    sa.Column('feat_rag_enabled', sa.Boolean(), nullable=True),
    sa.Column('feat_pdf_export', sa.Boolean(), nullable=True),
    sa.Column('feat_human_handoff', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('adm_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bot_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['bot_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_submissions')
    op.drop_table('bot_conversations')
    op.drop_table('adm_users')
    op.drop_table('adm_client_settings')
    op.drop_table('adm_clients')
    # ### end Alembic commands ###
