"""Add product catalog

Revision ID: 4e67549236ae
Revises: 6ed39306f339
Create Date: 2026-06-05 22:50:02.817572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e67549236ae'
down_revision: Union[str, Sequence[str], None] = '6ed39306f339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_catalog_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_rules', sa.Text(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('custom_attributes', sa.Text(), nullable=True),
    sa.Column('manage_stock', sa.Boolean(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adm_client_settings', sa.Column('feat_catalog', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_catalog_dynamic_fields', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adm_client_settings', 'feat_catalog_dynamic_fields')
    op.drop_column('adm_client_settings', 'feat_catalog')
    op.drop_table('data_catalog_products')
    # ### end Alembic commands ###
