"""Add feature flags

Revision ID: 6ed39306f339
Revises: bde26b796c05
Create Date: 2026-06-05 17:36:30.904901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6ed39306f339'
down_revision: Union[str, Sequence[str], None] = 'bde26b796c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adm_client_settings', sa.Column('feat_dashboard', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_history', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_contacts', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_submissions', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_appointments', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_gaps', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_channels', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_config', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_audit', sa.Boolean(), nullable=True))
    op.alter_column('adm_client_settings', 'reminder_24h_enabled',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('adm_client_settings', 'reminder_2h_enabled',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('data_knowledge', 'analyze_rag',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
    op.alter_column('data_knowledge', 'send_as_file',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
    op.alter_column('data_scheduling_exceptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getutcdate())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_scheduling_exceptions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(getutcdate())'))
    op.alter_column('data_knowledge', 'send_as_file',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
    op.alter_column('data_knowledge', 'analyze_rag',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
    op.alter_column('adm_client_settings', 'reminder_2h_enabled',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.alter_column('adm_client_settings', 'reminder_24h_enabled',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.drop_column('adm_client_settings', 'feat_audit')
    op.drop_column('adm_client_settings', 'feat_config')
    op.drop_column('adm_client_settings', 'feat_channels')
    op.drop_column('adm_client_settings', 'feat_gaps')
    op.drop_column('adm_client_settings', 'feat_appointments')
    op.drop_column('adm_client_settings', 'feat_submissions')
    op.drop_column('adm_client_settings', 'feat_contacts')
    op.drop_column('adm_client_settings', 'feat_history')
    op.drop_column('adm_client_settings', 'feat_dashboard')
    # ### end Alembic commands ###
