"""Add feature flags

Revision ID: 6ed39306f339
Revises: bde26b796c05
Create Date: 2026-06-05 17:36:30.904901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6ed39306f339'
down_revision: Union[str, Sequence[str], None] = 'bde26b796c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adm_client_settings', sa.Column('feat_dashboard', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_history', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_contacts', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_submissions', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_appointments', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_gaps', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_channels', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_config', sa.Boolean(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('feat_audit', sa.Boolean(), nullable=True))
    # reminder_24h_enabled/reminder_2h_enabled/analyze_rag/send_as_file: igual que en
    # c8bbc341c599, nunca las creó ninguna migración anterior (venían de una base pre-Alembic
    # manejada a mano). En una base nueva hay que crearlas, no alterarlas.
    op.add_column('adm_client_settings', sa.Column('reminder_24h_enabled', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    op.add_column('adm_client_settings', sa.Column('reminder_2h_enabled', sa.Boolean(), nullable=True, server_default=sa.text('0')))
    op.add_column('data_knowledge', sa.Column('analyze_rag', sa.Boolean(), nullable=True, server_default=sa.text('1')))
    op.add_column('data_knowledge', sa.Column('send_as_file', sa.Boolean(), nullable=True, server_default=sa.text('1')))
    # data_scheduling_exceptions ni siquiera existe como tabla en este punto de la cadena
    # (se crea recién en e7c1b5a9d4f0, ya con created_at nullable) — no hay nada que alterar acá.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_knowledge', 'send_as_file')
    op.drop_column('data_knowledge', 'analyze_rag')
    op.drop_column('adm_client_settings', 'reminder_2h_enabled')
    op.drop_column('adm_client_settings', 'reminder_24h_enabled')
    op.drop_column('adm_client_settings', 'feat_audit')
    op.drop_column('adm_client_settings', 'feat_config')
    op.drop_column('adm_client_settings', 'feat_channels')
    op.drop_column('adm_client_settings', 'feat_gaps')
    op.drop_column('adm_client_settings', 'feat_appointments')
    op.drop_column('adm_client_settings', 'feat_submissions')
    op.drop_column('adm_client_settings', 'feat_contacts')
    op.drop_column('adm_client_settings', 'feat_history')
    op.drop_column('adm_client_settings', 'feat_dashboard')
    # ### end Alembic commands ###
