"""Add welcome_media_path

Revision ID: c8bbc341c599
Revises: ee61a0c5c7d7
Create Date: 2026-05-21 14:58:56.838695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bbc341c599'
down_revision: Union[str, Sequence[str], None] = 'ee61a0c5c7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adm_client_settings', sa.Column('welcome_media_path', sa.String(length=255), nullable=True))
    # out_of_office_message / welcome_message_text nunca fueron creadas por ninguna migración anterior
    # (existían de antes en instalaciones viejas, hand-managed pre-Alembic). En una base nueva hay que
    # crearlas, no "alterarlas".
    op.add_column('adm_client_settings', sa.Column('out_of_office_message', sa.Text(), nullable=True))
    op.add_column('adm_client_settings', sa.Column('welcome_message_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adm_client_settings', 'welcome_message_text')
    op.drop_column('adm_client_settings', 'out_of_office_message')
    op.drop_column('adm_client_settings', 'welcome_media_path')
    # ### end Alembic commands ###
