"""Expansion de tablas SaaS Multi-Cliente

Revision ID: ee61a0c5c7d7
Revises: 0f23147c3831
Create Date: 2026-05-20 13:10:32.917946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee61a0c5c7d7'
down_revision: Union[str, Sequence[str], None] = '0f23147c3831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_menu_items',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('adm_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm_token_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_chat_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_pauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('paused_until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_session_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('is_deflected', sa.Boolean(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_phone', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('has_form', sa.Boolean(), nullable=True),
    sa.Column('form_fields', sa.Text(), nullable=True),
    sa.Column('storage_dest', sa.String(length=50), nullable=True),
    sa.Column('allow_scheduling', sa.Boolean(), nullable=True),
    sa.Column('interactive_options', sa.Text(), nullable=True),
    sa.Column('media_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_knowledge_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_proceedings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['adm_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('adm_user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('menu_key', sa.String(length=50), nullable=False),
    sa.Column('can_access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['adm_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adm_client_settings', sa.Column('google_sheet_id', sa.String(length=255), nullable=True))
    op.add_column('adm_client_settings', sa.Column('working_hours', sa.Text(), nullable=True))
    op.add_column('data_submissions', sa.Column('thread_id', sa.String(length=100), nullable=True))
    op.add_column('data_submissions', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('data_submissions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('data_submissions', 'status',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_submissions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('data_submissions', 'created_at')
    op.drop_column('data_submissions', 'topic')
    op.drop_column('data_submissions', 'thread_id')
    op.drop_column('adm_client_settings', 'working_hours')
    op.drop_column('adm_client_settings', 'google_sheet_id')
    op.drop_table('adm_user_permissions')
    op.drop_table('data_proceedings')
    op.drop_table('data_knowledge_gaps')
    op.drop_table('data_knowledge')
    op.drop_table('data_appointments')
    op.drop_table('bot_user_profiles')
    op.drop_table('bot_session_analytics')
    op.drop_table('bot_pauses')
    op.drop_table('bot_messages')
    op.drop_table('bot_chat_notes')
    op.drop_table('bot_attachments')
    op.drop_table('bot_alerts')
    op.drop_table('adm_token_usage')
    op.drop_table('adm_audit_logs')
    op.drop_table('adm_menu_items')
    # ### end Alembic commands ###
